import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the CSV data generated by the C++ simulator
df = pd.read_csv("miss.csv")

# 2. Compute the miss rate percentage for each window
# Avoid division by zero by checking if accesses > 0
df["miss_rate"] = (df["misses"] / df["accesses"]) * 100

# 3. Plotting the results
plt.figure(figsize=(10, 5))
plt.plot(
    df["window"],
    df["miss_rate"],
    marker="o",
    linestyle="-",
    color="b",
    label="Miss Rate (%)",
)

# 4. Graph Styling & Labels
plt.title(
    "Windowed Cache Miss-Rate Analysis (Temporal Locality)", fontsize=14, fontweight="bold"
)
plt.xlabel("Execution Window Index (per 1000 accesses)", fontsize=12)
plt.ylabel("Miss Rate (%)", fontsize=12)
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend()
plt.tight_layout()

# 5. Display the plot
plt.savefig("cache_miss_rate.png", dpi=300)
